[package]
name = "client"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]

[dependencies]
nix = "0.9.0"
libc = "0.2.29"
error-chain = "0.10.0"
transform = { path = "../transform" }
common = { path = "../common" }
